
ATTRIBUTION = "Powered by Xfinity"

ATTR_POLICY_NAME = 'policy_name'
ATTR_START_DATE = 'start_date'
ATTR_END_DATE = 'end_date'
ATTR_HOME_USAGE = 'home_usage'
ATTR_WIFI_USAGE = 'wifi_usage'
ATTR_TOTAL_USAGE = 'total_usage'
ATTR_ALLOWED_USAGE = 'allowed_usage'
ATTR_UNIT_OF_MEASURE = 'unit_of_measure'
ATTR_ADDITIONAL_BLOCKS_USED = 'additional_blocks_used'
ATTR_ADDITIONAL_COST_PER_BLOCK = 'additional_cost_per_block'
ATTR_ADDITIONAL_UNITS_PER_BLOCK = 'additional_units_per_block'
ATTR_ADDITIONAL_INCLUDED = 'additional_included'
ATTR_ADDITIONAL_USED = 'additional_used'
ATTR_ADDITIONAL_PERCENT_USED = 'additional_percent_used'
ATTR_ADDITIONAL_REMAINING = 'additional_remaining'
ATTR_BILLABLE_OVERAGE = 'billable_overage'
ATTR_OVERAGE_CHARGES = 'overage_charges'
ATTR_OVERAGE_USED = 'overage_used'
ATTR_CURRENT_CREDIT_AMOUNT = 'current_credit_amount'
ATTR_MAX_CREDIT_AMOUNT = 'max_credit_amount'
ATTR_POLICY = 'policy'
ATTR_COURTESY_USED = 'courtesy_used'
ATTR_COURTESY_REMAINING = 'courtesy_remaining'
ATTR_COURTESY_ALLOWED = 'courtesy_allowed'
ATTR_IN_PAID_OVERAGE = 'in_paid_overage'
ATTR_REMAINING_USAGE = 'remaining_usage'

DEFAULT_ICON = 'mdi:network'
DEFAULT_NAME = "Xfinity Usage"
